backend:
  name: github
  repo: caffeinated-tech/18cc
  branch: editing
  accept_roles:
    - admin
    - editor

publish_mode: editorial_workflow
media_folder: static/assets
public_folder: assets

collections:
  - name: post
    label: post
    folder: post
    create: true
    extension: json
    format: json
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
      