backend:
  name: github
  repo: caffeinated-tech/18cc
  branch: editing
  accept_roles:
    - admin
    - editor

publish_mode: editorial_workflow
media_folder: static/assets
public_folder: assets

collections:
  - name: post
    label: post
    folder: "content/post"
    create: true
    extension: json
    format: json
    fields:
      - { name: slug, label: Slug }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: titleImage, label: "Featured Image", widget: image }
      - { name: body, label: Body, widget: markdown }
      